# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: rabbit-depl
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: rabbit
#   template:
#     metadata:
#       labels:
#         app: rabbit
#     spec:
#       containers:
#       - name: rabbit
#         image: rabbitmq

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nats-srv
# spec:
#   selector:
#     app: nats
#   ports:
#     - name: client
#       protocol: TCP
#       port: 4222
#       targetPort: 4222
#     - name: monitoring
#       protocol: TCP
#       port: 8222
#       targetPort: 8222
